### ISSUE TITLE
Gallery Image is breaking 

### ISSUE THREAD

**Issue by roshni07** [weDevsOfficial/dokan-theme#32]
Description :

If you set more than four images on the product gallery the outlook is broken.

How to reproduce: 

1. Create a product 
2. Add more than four images on the gallery 

Expected behavior: 

The images should be side by side. 

Screenshot: https://prnt.sc/qtaqpo

**Comment by gidiyoo** [comment]
I am waiting for a solution for this problem.

**Comment by saimonh3** [comment]
https://github.com/weDevsOfficial/dokan-theme/pull/33
