### ISSUE TITLE
Outadted Woocommerce template

### ISSUE THREAD

**Issue by Commerces91** [weDevsOfficial/dokan-theme#34]
Hello, since the update of woocommerce 4.1.1, the Dokan theme
![unnamed](https://user-images.githubusercontent.com/65846685/82748584-8aac5000-9da3-11ea-9e65-477bfc7ea345.png)
 displays an error with outdated copy of files.

Please solve it. Thanks,

MM.

**Comment by saimonh3** [comment]
@Commerces91  Thanks, we'll release dokan theme soon. 
https://github.com/weDevsOfficial/dokan-theme/pull/35
